config/routes.rb
Rails.application.routes.draw do
  get '/' => "index#index"

  scope '/ir21' do
    get 'notification/index'

    resources :countries
    resources :change_histories
    resources :activities
    resources :network_section_fields
    resources :hermes_operators
    resources :organisations
    resources :users
    resources :user_sessions
    resources :network_sections
    resources :reports

    resources :exports do
      collection do
        get 'hermes-csv-export', to: 'exports#hermes_csv_export', as: "hermes_csv_export"
        get 'lte-sccp-ip-csv-export', to: 'exports#lte_sccp_ip_csv_export', format: 'csv'
        get 'lte-mno-ip-csv-export', to: 'exports#lte_mno_ip_csv_export', format: 'csv'
        get 'export-all-networks', to: 'exports#export_all_networks', format: 'xls'
        get 'export-all-networks-xlsx', to: 'exports#export_all_networks_xlsx', format: 'xlsx'
        get 'advanced-network-export', to: 'exports#export_all_networks_advanced', format: 'csv'
        get 'export-telenor-connexion', to: 'exports#export_telenor_connexion', format: 'xls'
        get 'generate-codes', to: 'exports#generate_codes', as: :generate_codes, format: 'csv'
        get 'generate-single-codes', to: 'exports#generate_single_codes', as: :generate_single_codes, format: 'xlsx'
        get 'sor-export', to: 'exports#sor_export', as: :sor_export, format: 'csv'
        get 'advanced-sor-export', to: 'exports#advanced_sor_export', as: :advanced_sor_export, format: 'csv'
        get 'sccp-ip-export', to: 'export#sccp_ip_export', as: :sccp_ip_export, format: 'csv'
      end
    end

    resources :imports do
      get 'resolve-conflict', to: "imports#resolve_conflict", as: "resolve-conflict"
      put 'link-pdf', to: 'imports#link_pdf', as: 'link_pdf'
      put 'mark-pdf-networks', to: 'imports#mark_pdf_networks', as: 'mark_pdf_networks'
      put 'unlink-pdf', to: 'imports#unlink_pdf', as: 'unlink_pdf'
      get 'resolve', to: 'imports#resolve', as: :resolve
      collection do
        get 'summery', to: 'imports#summery', as: 'summery'
      end
    end

    resources :networks do
      resources :versions
      get 'read-xml', to: "networks#read_xml", as: "read-xml"
      get 'read-excel', to: "networks#read_excel", as: "read-excel"
    end

    api_version(:module => "api/v1", :path => {:value => "api/v1"}, defaults: {format: 'json'}) do
      resources :organisations do
        collection do 
          get 'mulesoft', to: 'organisations#mulesoft', as: :mulesoft
          get 'line-ranges', to: 'organisations#line_ranges', as: :line_ranges
        end  
      end
      resources :networks
    end

    # Api for connexion
    api_version(:module => "api/v1/connexion", :path => {:value => "api/v1/connexion"}, defaults: {format: 'json'}) do
      resources :organisations do
        resources :networks
        collection do
          get 'all-network-details', to: 'networks#all_network_details'
        end
      end
    end

    root 'index#index'
    get 'read-pdf', to: "networks#read_pdf", as: "read-pdf"
    match 'search', to: 'search#index', as: 'search', via: [:POST,:GET]
    get 'sign-in', to: 'user_sessions#new', as: 'sign-in'
    get 'sign-out', to: 'user_sessions#destroy', as: 'sign-out'
    get 'revert/:id', to: 'versions#revert', as: 'revert'
    get 'forgot-password', to: 'users#forgot_password', as: 'forgot_password'
    put 'networks/:id/update_hstore_field', to: 'networks#update_hstore_field', as: 'network_update_hstore'
    put 'networks/:id/update_network_field', to: 'networks#update_network_field', as: 'network_update'
    put 'networks/:id/update_hstore_section_field', to: 'networks#update_hstore_section_field', as: 'network_section_update_hstore'
    put 'networks/:id/update_network_index_field', to: 'networks#update_network_index_field', as: 'network_update_index'
    get 'delete-row/:id', to: 'networks#delete_row'
    get 'active-imports', to: 'imports#active_imports', as: 'active-imports'
    get 'settings', to: 'index#settings', as: 'settings'
    get 'change-password', to: 'users#change_password', as: 'change_password'
    post 'send-reset-password', to: 'users#send_reset_password', as: 'reset_password'
    get 'run-rake-import', to: 'imports#run_import', as: 'run_rake_import'
    match 'remote-login', to: 'user_sessions#remote_login', via: [:POST,:GET]
    put 'network-section-update-field', to: 'network_section_fields#update_field'
    get 'soap-test', to: 'imports#soap_test', as: 'soap-test'
    get 'import-diff', to: 'index#import_diffs', as: 'import_diff'
    get 'flagged-networks', to: 'networks#flagged_networks', as: 'flagged_networks'
    get 'import-files', to: 'imports#import_files', as: 'import_files'
    get 'read-file/:id', to: 'imports#read_file', as: 'read_file'
    get 'show-diff-snapshot/:id', to: 'networks#show_diff_snapshot', as: 'show_diff_snapshot'
    post 'add-line-range', to: 'networks#add_line_range', as: 'add_line_range'
    put 'edit-linerange', to: 'networks#edit_linerange',as: 'edit-line-range', format: 'js'
    delete 'delete-line-range/:id', to: 'networks#delete_line_range', as: 'delete_line_range'
    get 'notifications', to: 'notification#index', as: :notifications
    match 'add-role', to: 'users#add_role', as: :add_role, via: [:POST,:GET]
    get 'delete-role', to: 'users#remove_role', as: :delete_role
    get 'download-export', to: 'exports#download_export', as: :download_export
    get 'notify-groups', to: "notification#notify_groups", as: :notify_groups
    get 'notify-group/:id', to: "notification#notify_group", as: :notify_group
    post 'add-notify-group-profile', to: "notification#add_profile", as: :add_notify_group_profile
    get 'show-notify-networks', to: 'notification#show_networks', as: :show_notify_networks, format: 'js'
    post 'add-notify-group-network', to: "notification#add_network", as: :add_notify_group_network
    post 'add-notify-group-organisation', to: 'notification#add_organisation', as: :add_notify_group_organisation
    match 'lazy-load-line-ranges', to: 'networks#lazy_load_line_ranges', as: :lazy_load_line_ranges, via: [:POST, :GET, :PUT]
    match 'lazy-load-network-sections', to: 'networks#lazy_load_network_sections', as: :lazy_load_network_sections, via: [:POST, :GET, :PUT]
    delete 'delete-notify-group/:id', to: 'notification#delete_notify_group', as: :delete_notify_group
    get 'add_notify_group_to_user', to: 'notification#add_notify_group_to_user', as: :add_notify_group_to_user
    get 'activate-all-imports', to: 'imports#activate_all_imports', as: :activate_all_imports
    delete 'delete-network-from-notify-group', to: 'networks#delete_from_notify_group', as: :delete_network_from_notify_group
    delete 'delete-organisation-from-notify-group', to: 'organistions#delete_from_notify_group', as: :delete_organisation_from_notify_group
    delete 'delete-notify-group-from-user', to: 'users#delete_from_notify_group', as: :delete_from_notify_group
    get 'show-network-comment', to: 'networks#show_network_comment', as: :show_network_comment, defaults: {format: 'js'}
    match 'add-notify-setting-to-user', to: 'notification#add_notify_setting_to_user', as: :add_notify_setting_to_user, defaults: {format: 'js'}, via: [:POST,:GET]
    match 'remove-notify-setting-from-user', to: 'notification#remove_notify_setting_from_user', as: :remove_notify_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET] 
    match 'add-view-setting-to-user', to: 'users#add_view_setting_to_user', as: :add_view_setting_to_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'remove-view-setting-from-user', to: 'users#remove_view_setting_from_user', as: :remove_view_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'upload-sms-hub-file', to: 'imports#upload_sms_hub_file', as: :upload_sms_hub_file, via: [:POST, :GET]
    match 'customized-exports', to: 'exports#customized_exports', as: :customized_exports, via: [:POST, :GET]
    get 'create-manual-export', to: 'exports#create_manual_export', as: :create_manual_export
    get 'view-settings', to: 'index#view_settings', as: :view_settings
    get 'show-sms-hub-data', to: 'index#show_sms_hub_data', as: :show_sms_hub_data
    get 'get-rest-of-networks', to: 'networks#get_rest_of_networks', as: :get_rest_of_networks
    get 'get-rest-of-networks-dynamic/:id', to: 'networks#get_rest_of_networks_dynamic', as: :get_rest_of_networks_dynamic
    match 'export-ip-addresses', to: 'exports#export_ip_addresses', as: :export_ip_addresses, via: [:POST, :GET]
    get 'line-range-overview-ir21', to: 'index#line_range_overview_ir21', as: :line_range_overview_ir21
    get 'line-range-overview-export', to: 'index#line_range_overview_export', as: :line_range_overview_export
    get 'line-range-code-export', to: 'index#line_range_code_export', as: :line_range_code_export
    get 'import-details/:id', to: 'imports#import_details', as: :import_details
    get 'create-missing-structutre', to: 'imports#create_missing_structure', as: :create_missing_structure
    post 'get-sms-hub-data', to: 'index#line_range_overview_export_ajax_data', as: :line_range_overview_export_ajax_data, format: :js 
    post 'get-code-data', to: 'index#line_range_overview_code_ajax_data', as: :line_range_overview_code_ajax_data, format: 'js' 
    patch 'change-network-status', to: 'networks#change_network_status', as: :change_network_status
    get 'mno-ip-overview', to: 'index#mno_ip_overview', as: :mno_ip_overview
    post 'update-mno-sccp-ip', to: 'index#update_mno_sccp_ip', as: :update_mno_sccp_ip
    get 'add-mno-ip-line', to: 'index#add_mno_ip_line', as: :add_mno_ip_line
    get 'add-sccp-ip-line', to: 'index#add_sccp_ip_line', as: :add_sccp_ip_line
  end


##### PLAIN ROUTE SECTION ########################################
# Theese extra route exist to render proxy correct
# It makes it possible to each render /ir21 scope and plain url´s
#
###################################################################

app/controllers/api/v1/connexion/networks_controller.rb
class Api::V1::Connexion::NetworksController < ApplicationController
  skip_before_action :require_login
  http_basic_authenticate_with name: "connexion", password: "dRe6RtW"
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  def index
    @networks = Network.where(organisation_id: params[:organisation_id])
  end

  def show
    @network = Network.find(params[:id])
    ns = NetworkSection.where(field_name: 'ip_roaming_info').first
    @ip_address =  NetworkRow.where(network_id: @network.id, network_section_id: ns.id).first.data
    @gt_number_ranges = NetworkRow.where("network_section_id = 167 AND network_id = ?", params[:id]).first
  end

  def all_network_details
    respond_to do |format|
      format.json {
        @organisations = Organisation.order("updated_at DESC").all
        @ns = NetworkSection.where(field_name: 'ip_roaming_info').first        
      }
    end
  end


  def connexion
     @networks = Network.all  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:organisation_id, :tadig_code, :network_name, :terrestrial, :presentation_of_country_initials_and_mnn, :abbreviated_mnn, :network_color_code, :source)
    end
end

app/controllers/api/v1/networks_controller.rb
class Api::V1::NetworksController < ApplicationController
  skip_before_action :require_login
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  def index
    @networks = Network.all
  end

  def show
    # Realms in LTE section
    # Country iso code
    # Country full name
    # CC - country code
    # Tad code - Tadig code
    # Network name - Organisation name
    # Ip address - Ip roaming IW info general
    # Ip netmask - IP Roaming IW general IpAdressOrRange
    # Ndc = ndc (CCITT_E214_MGT (NC number))
    # Gobal title. =  GT number ranges 
    # Operator name = Organisation name ? Check if network name I filled for above
    # Technology = ?
  end


  def connexion
     @networks = Network.all  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:organisation_id, :tadig_code, :network_name, :terrestrial, :presentation_of_country_initials_and_mnn, :abbreviated_mnn, :network_color_code, :source)
    end
end

app/helpers/networks_helper.rb
module NetworksHelper
	# function to iterate over deep level hash
	def walk_tree(tree,depth= 0, &blk)
		Rails.cache.fetch("#{tree}/tree") do
			return enum_for(:walk_tree, depth) unless blk
			
			yield tree, depth
			
			tree.each do |node|
				unless node.is_a?(String)
					walk_tree(node, depth + 1, &blk)
				end
			end
		end
	end

	def get_dpc_hex(network)
		ns = NetworkSection.where(field_name: "international_dpc_item").first
		nr = Rails.cache.fetch("#{network}/dpc_hex") do NetworkRow.where(network_id: network.id, network_section_id: ns.try(:id)).first end
		if nr
			if nr.data["dpc-hex"]
				return nr.data["dpc-hex"]
			end
			if nr.data["dpc_hex"]
				return nr.data["dpc_hex"]
			end 
			dpc = NetworkRow.where(network_section_id: 149, network_id: network.id).first
			split = dpc.data['dpc'].split('-')
			split = dpc.data['dpc'].split('_') if split.nil?
			return result = split[0].to_i * 2048 + split[1].to_i * 8 + split[2].to_i
		end
	end

	def get_dpc_decimal(network)
		ns = NetworkSection.where(field_name: "international_dpc_item").first
		nr = Rails.cache.fetch("#{network}/dpc_decimal") do NetworkRow.where(network_id: network.id, network_section_id: ns.try(:id)).first end
		if nr
			if nr.data["dpc-decimal"] 
				return nr.data["dpc-decimal"] 
			end
			if nr.data["dpc_decimal"]
				return nr.data["dpc_decimal"]
			end
			
			dpc = NetworkRow.where(network_section_id: 149, network_id: network.id).first
			split = dpc.data['dpc'].split('-')
			split = dpc.data['dpc'].split('_') if split.nil?
			result = split[0].to_i * 2048 + split[1].to_i * 8 + split[2].to_i
			return result.to_s(16)
		end
	end

	def get_sc_type(network)
		ns = network_section = NetworkSection.where(field_name: "international_dpc_item").first
		nr = NetworkRow.where(network_id: network.id, network_section_id: ns.try(:id)).first
		nr.data["sc_type"] if nr
	end

	def get_country_code(network)
		if network.routing
			network.routing["e214_cc"]
		else
			"No country defined"
		end
	end
end

app/views/networks/_modal_show_comment.html.erb
<div class="modal fade modal<%= network.id %>" id="show_comment_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add comment</h4>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_for(network) do |f| %>
        <div class="field">
          <%= f.text_area :comment, rows: "10" %>
        </div>
        <div class="clearfix"></div>
        <div class="actions">
          <%= f.submit %>
        </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/networks/_new_line_range_modal.html.erb
<div class="modal fade" id="linerangeModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add new line range</h4>
      </div>
      <div class="modal-body">
      <br/><br/>
        <%= form_tag("/add-line-range") do |f| %>
          <%= text_field_tag(:start_range, nil, placeholder: "Start range") %>
          <%= text_field_tag(:stop_range, nil, placeholder: "Stop Range") %>
          <%= hidden_field_tag(:network_id, @network.id) %>
          <%= submit_tag('Add line range', class: "btn")%>
        <% end %>
        <br/><br/>
        <div class="clearfix"></div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/networks/_sections_modal.html.erb
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Choose section to add</h4>
      </div>
      <div class="modal-body">
        <% @inactive_sections.each do |section| %>
          <div class="name" id="<%= section.id %>" data-name="<%= section.name %>">
            <%= section.name %>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/networks/_spy_navigation.html.erb
<div id="navbar-spy">
	<ul class="nav navbar-nav" role="tablist">
		<li class="active">
			<a href="#routing" class="active">
				<div class="selected"></div>
				Routing
			</a>
		</li>
		<li>
			<a href="#international-sccp-carrier">
				International Sccp Carrier
			</a>
		</li>
		<li>
		<li>
			<a href="#ip-roaming-info">
				Ip Roaming info
			</a>
		</li>
		<% if @network.network_rows.where(network_section_id: 57).first %>
		<li>
			<a href="#lteinfosection">
				Lte section
			</a>
		</li>
		<% end %>
	</ul>
</div>

app/views/networks/edit.html.erb
<h1>Editing Network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/flagged_networks.html.erb
<h1>Changed Section Overview</h1>
<table class="table-responsive table-striped networks sortable">
	<thead style="white-space: nowrap;">
		<tr>
			<th>Date</th>
			<th>Name</th>
			<th>Tadig</th>
			<th>message</th>
			<th>File</th>
			<th>Effective date of change</th>
			<th>Snapshot</th>
		</tr>
	</thead>
	<tbody>
		<% @network_diffs.each do |diff| %>
		
		<tr class="network">
			<td>
				<div class="green_dot">
					
				</div>
				<%= diff.created_at %>
			</td>
			<td>
				<%= link_to diff.network do %><%= diff.network.try(:display_name) %><% end %>
			</td>
			<td>
				<%= diff.network.try(:tadig_code) %>
			</td>
			<!-- Removing some hard coded error messages done in early phase -->
			<td>
				<%= diff.message.sub('does not match latest import', '') %>
			</td>
			<td>
				<% case diff.network.try(:import).try(:file_type) %>
				<% when 'xml' %>
				<%= link_to network_read_xml_path(diff.network) do %>
				<i class='fa fa-file-code-o'></i>
				<% end %>
				<% when 'xlsx' %>
				<%= link_to network_read_excel_path(diff.network) do %>
				<i class="fa fa-file-excel-o"></i>
				<% end %>
				<% end %>
			</td>
			<td>
			<% if diff.section_id == 0 %>
				<% if diff.network  %>
				<%= diff.network.routing["effective_date_of_change"] %>
				<% end %>
			<% else %>
				<%= NetworkRow.where(network_section_id: diff.section_id, network_id: diff.network_id).last
							.try(:effective_date_of_change) %>
			<% end %>
			</td>
			<td>
			<% if diff.snapshot %>
				<%= link_to(truncate(diff.snapshot.strip, length: 60), show_diff_snapshot_path(diff.id))  %>
			<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/networks/get_rest_of_networks.html.erb
  <% cache([@networks, @caching_profile], public: :true) do %>
   <% @networks.order('parent_id desc').sort_by(&:updated_at).reverse.each do |network| %>
   <% @current = network %>
   <% @previous = nil unless @previous %>
   <tr style="cursor: pointer" class="network-row <% if @previous.try(:organisation_id) == network.organisation_id %>indent<% end %>" id="<%= network.id %>">
    <td class="edit" data-type-name="organisation_name"><div class="name"><%= network.organisation.try(:name) %></div></td>
    <!-- Only show for admins -->
    <td class="edit" data-type-name="organisation_id">
        <%= network.organisation_id %>
    </td>
    <td class="edit" data-type-name="display_name"><%= network.try(:display_name) %></td>
    <td class="edit" data-type-name="country_name"><%= network.country.try(:name) %></td>
    <td class="edit" data-type-name="network_name"><%= network.try(:network_name) %></td>
    <td class="edit" data-type-name="e212_mcc"><%= network.routing["e212_mcc"] if network.routing %></td>
    <td class="edit" data-type-name="e212_mnc">
      <%= network.routing["e212_mnc"] if network.routing %>
    </td>
    <td class="edit" data-type-name="country_code">
      <%= get_country_code(network) %>
    </td>
    <td class="edit" data-type-name="e214_nc">
      <div class="e214_nc">
        <%= network.routing["e214_nc"] if network.routing %>
      </div>
    </td>
    <td class="edit" data-type-name="file_type"><%= network.try(:import).try(:file_type) %></td>
    <td class="edit" data-type-name="file_creation_date"><%= network.try(:xml_creation_date) %></td>
    <td class="comment" data-network-id="<%= network.id %>" style="text-align: center;" data-toggle="modal" data-target="#modal_show_comment">
      <% if network.comment %>
      <i class="fa fa-comment comment" data-network-id="<%= network.id %>" aria-hidden="true"></i>
      <% else %>
      <i class="fa fa-comment-o comment" data-network-id="<%= network.id %>" aria-hidden="true"></i>
      <% end %>
    </td>
    <td class="edit" data-type-name="tadig"><%= network.try(:tadig_code) %></td>
    <% if current_user.has_role? :superadmin %>
      <td class="edit" data-type-name="rosi_id"><%= network.try(:rosi_id) %></td>
    <% end %>
    <td class="delete"><%= link_to network, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" do %>
      <i class="fa fa-times delete"></i>
      <% end %>
    </td>
  </tr>
  <% @previous = @current %>
  <% end %>
  <% end %>

app/views/networks/lazy_load_line_ranges.html.erb
<!-- Line ranges -->
<% unless @network.try(:network_line_ranges).blank? %>
<h3 class="section-title">
  Line ranges <i class="fa fa-plus-square" data-toggle="modal" data-target="#linerangeModal"></i>
</h3>
<div class="collaps">
  <div data-section-id="line_ranges" class="show-collapsed">
    Show <i class="fa fa-plus-square"></i>
  </div>
  <div data-section-id="line_ranges" class="hide-collapsed">
    Hide <i class="fa fa-minus-square"></i>
  </div>
</div>
<table class="table table-striped collapsed" id="table_line_ranges">
  <thead>
    <tr>
      <td>Start</td>
      <td>Stop</td>
      <td></td>
    </tr>

  </thead>
  <tbody>
    <% @network.network_line_ranges.where("removed is NOT true").order("range_start").each do |range| %>
    <tr>
      <td class="edit edit-line-range" data-type="range_start" data-id="<%= range.id %>" id="range_start_<%= range.id %>">
        <%= range.range_start %>
      </td>
      <td class="edit edit-line-range" data-type="range_stop" data-id="<%= range.id %>" id="range_stop_<%= range.id %>">
        <%= range.range_stop %>
      </td>
      <td class="delete"><%= link_to "delete", delete_line_range_path(range.id), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<!-- /Line ranges -->

<!-- Sms hub line ranges -->
<% if current_user.has_role? :superadmin %>
<% unless @network.try(:sms_hub_line_ranges).blank? %>
<h3 class="section-title">
  SMS hub line ranges
</h3>
<div class="collaps">
    <div data-section-id="sms_hub_ranges" class="show-collapsed">
      Show <i class="fa fa-plus-square"></i>
    </div>
    <div data-section-id="sms_hub_ranges" class="hide-collapsed">
      Hide <i class="fa fa-minus-square"></i>
    </div>
  </div>
<table class="table table-striped collapsed sortable" id="table_sms_hub_ranges">
  <thead>
    <tr>
      <td>Start</td>
      <td></td>
    </tr>

  </thead>
  <tbody>
    <% @network.sms_hub_line_ranges.order("range_start").each do |range| %>
    <tr>
      <td class="edit edit-line-range" data-type="range_start" data-sms-hub="true" data-id="<%= range.id %>" id="range_start_<%= range.id %>" <% if range.removed %>style="color: red"<% end %>>
        <%= range.range_start %>  
        <% if range.message %>
        <span style="color: #434343; font-size: 12px;">( <%= range.message %> )</span>
        <% end %>
      </td>
      <td class="delete">
        <%= link_to "delete", delete_line_range_path(range.id, sms_hub: true), method: :delete %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<% end %>
<!-- /Sms hub line ranges -->

app/views/networks/new.html.erb
<h1>New Network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>

app/views/networks/show_diff_snapshot.html.erb
<style>
	<%= Diffy::CSS %>

</style>
<%= render 'layouts/back_navigation' %>
<h1>Snapshot of diff</h1>
<% v1 = @diff.snapshot.split('=================================================').first.strip %>
<% v2 = @diff.snapshot.split('=================================================').second.strip %>
<hr/>
<h4>Diffrencies</h4>
<% if v1.blank? %>
Section not found in previous version
<% end %>
<%= Diffy::Diff.new(v1,v2, :context => 100, format: :html, :include_plus_and_minus_in_html => true).to_s(:html).html_safe %>

app/views/networks/update.js.erb
console.log('updated');