config/routes.rb
Rails.application.routes.draw do
  get '/' => "index#index"

  scope '/ir21' do
    get 'notification/index'

    resources :countries
    resources :change_histories
    resources :activities
    resources :network_section_fields
    resources :hermes_operators
    resources :organisations
    resources :users
    resources :user_sessions
    resources :network_sections
    resources :reports

    resources :exports do
      collection do
        get 'hermes-csv-export', to: 'exports#hermes_csv_export', as: "hermes_csv_export"
        get 'lte-sccp-ip-csv-export', to: 'exports#lte_sccp_ip_csv_export', format: 'csv'
        get 'lte-mno-ip-csv-export', to: 'exports#lte_mno_ip_csv_export', format: 'csv'
        get 'export-all-networks', to: 'exports#export_all_networks', format: 'xls'
        get 'export-all-networks-xlsx', to: 'exports#export_all_networks_xlsx', format: 'xlsx'
        get 'advanced-network-export', to: 'exports#export_all_networks_advanced', format: 'csv'
        get 'export-telenor-connexion', to: 'exports#export_telenor_connexion', format: 'xls'
        get 'generate-codes', to: 'exports#generate_codes', as: :generate_codes, format: 'csv'
        get 'generate-single-codes', to: 'exports#generate_single_codes', as: :generate_single_codes, format: 'xlsx'
        get 'sor-export', to: 'exports#sor_export', as: :sor_export, format: 'csv'
        get 'advanced-sor-export', to: 'exports#advanced_sor_export', as: :advanced_sor_export, format: 'csv'
        get 'sccp-ip-export', to: 'export#sccp_ip_export', as: :sccp_ip_export, format: 'csv'
      end
    end

    resources :imports do
      get 'resolve-conflict', to: "imports#resolve_conflict", as: "resolve-conflict"
      put 'link-pdf', to: 'imports#link_pdf', as: 'link_pdf'
      put 'mark-pdf-networks', to: 'imports#mark_pdf_networks', as: 'mark_pdf_networks'
      put 'unlink-pdf', to: 'imports#unlink_pdf', as: 'unlink_pdf'
      get 'resolve', to: 'imports#resolve', as: :resolve
      collection do
        get 'summery', to: 'imports#summery', as: 'summery'
      end
    end

    resources :networks do
      resources :versions
      get 'read-xml', to: "networks#read_xml", as: "read-xml"
      get 'read-excel', to: "networks#read_excel", as: "read-excel"
    end

    api_version(:module => "api/v1", :path => {:value => "api/v1"}, defaults: {format: 'json'}) do
      resources :organisations do
        collection do 
          get 'mulesoft', to: 'organisations#mulesoft', as: :mulesoft
          get 'line-ranges', to: 'organisations#line_ranges', as: :line_ranges
        end  
      end
      resources :networks
    end

    # Api for connexion
    api_version(:module => "api/v1/connexion", :path => {:value => "api/v1/connexion"}, defaults: {format: 'json'}) do
      resources :organisations do
        resources :networks
        collection do
          get 'all-network-details', to: 'networks#all_network_details'
        end
      end
    end

    root 'index#index'
    get 'read-pdf', to: "networks#read_pdf", as: "read-pdf"
    match 'search', to: 'search#index', as: 'search', via: [:POST,:GET]
    get 'sign-in', to: 'user_sessions#new', as: 'sign-in'
    get 'sign-out', to: 'user_sessions#destroy', as: 'sign-out'
    get 'revert/:id', to: 'versions#revert', as: 'revert'
    get 'forgot-password', to: 'users#forgot_password', as: 'forgot_password'
    put 'networks/:id/update_hstore_field', to: 'networks#update_hstore_field', as: 'network_update_hstore'
    put 'networks/:id/update_network_field', to: 'networks#update_network_field', as: 'network_update'
    put 'networks/:id/update_hstore_section_field', to: 'networks#update_hstore_section_field', as: 'network_section_update_hstore'
    put 'networks/:id/update_network_index_field', to: 'networks#update_network_index_field', as: 'network_update_index'
    get 'delete-row/:id', to: 'networks#delete_row'
    get 'active-imports', to: 'imports#active_imports', as: 'active-imports'
    get 'settings', to: 'index#settings', as: 'settings'
    get 'change-password', to: 'users#change_password', as: 'change_password'
    post 'send-reset-password', to: 'users#send_reset_password', as: 'reset_password'
    get 'run-rake-import', to: 'imports#run_import', as: 'run_rake_import'
    match 'remote-login', to: 'user_sessions#remote_login', via: [:POST,:GET]
    put 'network-section-update-field', to: 'network_section_fields#update_field'
    get 'soap-test', to: 'imports#soap_test', as: 'soap-test'
    get 'import-diff', to: 'index#import_diffs', as: 'import_diff'
    get 'flagged-networks', to: 'networks#flagged_networks', as: 'flagged_networks'
    get 'import-files', to: 'imports#import_files', as: 'import_files'
    get 'read-file/:id', to: 'imports#read_file', as: 'read_file'
    get 'show-diff-snapshot/:id', to: 'networks#show_diff_snapshot', as: 'show_diff_snapshot'
    post 'add-line-range', to: 'networks#add_line_range', as: 'add_line_range'
    put 'edit-linerange', to: 'networks#edit_linerange',as: 'edit-line-range', format: 'js'
    delete 'delete-line-range/:id', to: 'networks#delete_line_range', as: 'delete_line_range'
    get 'notifications', to: 'notification#index', as: :notifications
    match 'add-role', to: 'users#add_role', as: :add_role, via: [:POST,:GET]
    get 'delete-role', to: 'users#remove_role', as: :delete_role
    get 'download-export', to: 'exports#download_export', as: :download_export
    get 'notify-groups', to: "notification#notify_groups", as: :notify_groups
    get 'notify-group/:id', to: "notification#notify_group", as: :notify_group
    post 'add-notify-group-profile', to: "notification#add_profile", as: :add_notify_group_profile
    get 'show-notify-networks', to: 'notification#show_networks', as: :show_notify_networks, format: 'js'
    post 'add-notify-group-network', to: "notification#add_network", as: :add_notify_group_network
    post 'add-notify-group-organisation', to: 'notification#add_organisation', as: :add_notify_group_organisation
    match 'lazy-load-line-ranges', to: 'networks#lazy_load_line_ranges', as: :lazy_load_line_ranges, via: [:POST, :GET, :PUT]
    match 'lazy-load-network-sections', to: 'networks#lazy_load_network_sections', as: :lazy_load_network_sections, via: [:POST, :GET, :PUT]
    delete 'delete-notify-group/:id', to: 'notification#delete_notify_group', as: :delete_notify_group
    get 'add_notify_group_to_user', to: 'notification#add_notify_group_to_user', as: :add_notify_group_to_user
    get 'activate-all-imports', to: 'imports#activate_all_imports', as: :activate_all_imports
    delete 'delete-network-from-notify-group', to: 'networks#delete_from_notify_group', as: :delete_network_from_notify_group
    delete 'delete-organisation-from-notify-group', to: 'organistions#delete_from_notify_group', as: :delete_organisation_from_notify_group
    delete 'delete-notify-group-from-user', to: 'users#delete_from_notify_group', as: :delete_from_notify_group
    get 'show-network-comment', to: 'networks#show_network_comment', as: :show_network_comment, defaults: {format: 'js'}
    match 'add-notify-setting-to-user', to: 'notification#add_notify_setting_to_user', as: :add_notify_setting_to_user, defaults: {format: 'js'}, via: [:POST,:GET]
    match 'remove-notify-setting-from-user', to: 'notification#remove_notify_setting_from_user', as: :remove_notify_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET] 
    match 'add-view-setting-to-user', to: 'users#add_view_setting_to_user', as: :add_view_setting_to_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'remove-view-setting-from-user', to: 'users#remove_view_setting_from_user', as: :remove_view_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'upload-sms-hub-file', to: 'imports#upload_sms_hub_file', as: :upload_sms_hub_file, via: [:POST, :GET]
    match 'customized-exports', to: 'exports#customized_exports', as: :customized_exports, via: [:POST, :GET]
    get 'create-manual-export', to: 'exports#create_manual_export', as: :create_manual_export
    get 'view-settings', to: 'index#view_settings', as: :view_settings
    get 'show-sms-hub-data', to: 'index#show_sms_hub_data', as: :show_sms_hub_data
    get 'get-rest-of-networks', to: 'networks#get_rest_of_networks', as: :get_rest_of_networks
    get 'get-rest-of-networks-dynamic/:id', to: 'networks#get_rest_of_networks_dynamic', as: :get_rest_of_networks_dynamic
    match 'export-ip-addresses', to: 'exports#export_ip_addresses', as: :export_ip_addresses, via: [:POST, :GET]
    get 'line-range-overview-ir21', to: 'index#line_range_overview_ir21', as: :line_range_overview_ir21
    get 'line-range-overview-export', to: 'index#line_range_overview_export', as: :line_range_overview_export
    get 'line-range-code-export', to: 'index#line_range_code_export', as: :line_range_code_export
    get 'import-details/:id', to: 'imports#import_details', as: :import_details
    get 'create-missing-structutre', to: 'imports#create_missing_structure', as: :create_missing_structure
    post 'get-sms-hub-data', to: 'index#line_range_overview_export_ajax_data', as: :line_range_overview_export_ajax_data, format: :js 
    post 'get-code-data', to: 'index#line_range_overview_code_ajax_data', as: :line_range_overview_code_ajax_data, format: 'js' 
    patch 'change-network-status', to: 'networks#change_network_status', as: :change_network_status
    get 'mno-ip-overview', to: 'index#mno_ip_overview', as: :mno_ip_overview
    post 'update-mno-sccp-ip', to: 'index#update_mno_sccp_ip', as: :update_mno_sccp_ip
    get 'add-mno-ip-line', to: 'index#add_mno_ip_line', as: :add_mno_ip_line
    get 'add-sccp-ip-line', to: 'index#add_sccp_ip_line', as: :add_sccp_ip_line
  end


##### PLAIN ROUTE SECTION ########################################
# Theese extra route exist to render proxy correct
# It makes it possible to each render /ir21 scope and plain url´s
#
###################################################################

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  has_many :pdf_networks
  has_many :networks, through: :pdf_networks
  belongs_to :import
end

app/views/index/_line_range_code_partial.html.erb
<% line_ranges.each do |range| %>
<tr>
  <td class="smshub-name">
    <%= range.code.try(:network).try(:organisation).try(:name) %>
  </td>
  <td class="range-start" <% if range.removed == true %> style="color: #EB274B" <% end %>>
    <%= range.range_start %>
  </td>
  <td class="display-name">
    <%= range.code.imsi %>
  </td>
  <td>
    <% if range.message %>
    <%= range.message.gsub('overlapping', 'overlapped by').gsub('of', '').gsub('ranges', 'range ID') %>
    <% end %>
  </td>
  <td><%= range.code.imported_from %></td>
</tr>
<% end %>

app/views/index/_line_range_export_partial.html.erb
<% line_ranges.each do |range| %>
<tr>
  <td class="smshub-name">
    <%= range.sms_hub.try(:network).try(:organisation).try(:name) %>
  </td>
  <td class="range-start" <% if range.removed == true %> style="color: #EB274B" <% end %>>
    <%= range.range_start %>
  </td>
  <td class="display-name">
    <%= range.sms_hub.imsi %>
  </td>
  <td>
    <% if range.message %>
    <%= range.message.gsub('overlapping', 'overlapped by').gsub('of', '').gsub('ranges', 'range ID') %>
    <% end %>
  </td>
  <td><%= range.sms_hub.imported_from %></td>
</tr>
<% end %>

app/views/index/import_diffs.html.erb
<h1>Import status - hermes</h1>

<h4><%= @hermes_unmatched.count %> unmatched</h4>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>HERMES</th>
        <th>IR21</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @hermes_unmatched) do |hermes_operator| %>
      <td>
        Id: <%= hermes_operator.data['sms_number_administration_id'] %><br/>
        Country: <%= hermes_operator.data['country'] %><br/>
        Carrier: <%= hermes_operator.data['carrier'] %><br/>
        
        <%
        if hermes_operator.data['imsi_range'].include?('-')
          imsi_range = hermes_operator.data['imsi_range'].split('-')
        else
          imsi_range = hermes_operator.data['imsi_range'].split(' ')
        end
        %>
        <% if hermes_operator.network %>
        <% unless imsi_range[0] ==  hermes_operator.network.routing['e212_mcc'] %>
          <div style="background-color: yellow">
        <% end end %>
        
        MCC: <%= imsi_range[0] %><br/>

        <% if hermes_operator.network %>
        <% unless imsi_range[0] ==  hermes_operator.network.routing['e212_mcc']  %>
          </div>
        <% end end %>
        
        <% if hermes_operator.network %>
        <% unless imsi_range[1] ==  hermes_operator.network.routing['e212_mnc'] %>
          <div style="background-color: yellow">
        <% end end %>
        MNC: <%= imsi_range[1] %><br/>
        
        <% if hermes_operator.network %>
        <% unless imsi_range[1] ==  hermes_operator.network.routing['e212_mnc'] %>
          </div>
        <% end end %>
      </td>
      <td style="max-width: 200px;">
      <div class="imsi">
        <% if hermes_operator.network %>
        ROSI_ID: <%= hermes_operator.try(:network).try(:rosi_id) %><br/>
        Carrier: <%= hermes_operator.try(:network).try(:display_name) %><br/>
        MCC: <%= hermes_operator.network.routing['e212_mcc'] %><br/>
        MNC: <%= hermes_operator.network.routing['e212_mnc'] %><br/>
        <% end %>
      </div>
      </td>
      <td><%= link_to 'Destroy', hermes_operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/index/import_diffs_old.html.erb
<h1>Import status</h1>

<h4>Hermes import</h4>
<strong><%= @hermes_imports.count %></strong> rows and <strong><%= @hermes_matches.count %></strong> matches, showing matches on top
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>HERMES</th>
        <th>IR21</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @hermes_imports) do |hermes_operator| %>
      <td>
        Id: <%= hermes_operator.data['sms_number_administration_id'] %><br/>
        Country: <%= hermes_operator.data['country'] %><br/>
        Carrier: <%= hermes_operator.data['carrier'] %><br/>
        
        <%
        if hermes_operator.data['imsi_range'].include?('-')
          imsi_range = hermes_operator.data['imsi_range'].split('-')
        else
          imsi_range = hermes_operator.data['imsi_range'].split(' ')
        end
        %>
        <% if hermes_operator.network %>
        <% unless imsi_range[0] ==  hermes_operator.network.routing['e212_mcc'] %>
          <div style="background-color: yellow">
        <% end end %>
        
        MCC: <%= imsi_range[0] %><br/>

        <% if hermes_operator.network %>
        <% unless imsi_range[0] ==  hermes_operator.network.routing['e212_mcc']  %>
          </div>
        <% end end %>
        
        <% if hermes_operator.network %>
        <% unless imsi_range[1] ==  hermes_operator.network.routing['e212_mnc'] %>
          <div style="background-color: yellow">
        <% end end %>
        MNC: <%= imsi_range[1] %><br/>
        
        <% if hermes_operator.network %>
        <% unless imsi_range[1] ==  hermes_operator.network.routing['e212_mnc'] %>
          </div>
        <% end end %>
      </td>
      <td style="max-width: 200px;">
      <div class="imsi">
        <% if hermes_operator.network %>
        ROSI_ID: <%= hermes_operator.try(:network).try(:rosi_id) %><br/>
        Carrier: <%= hermes_operator.try(:network).try(:display_name) %><br/>
        MCC: <%= hermes_operator.network.routing['e212_mcc'] %><br/>
        MNC: <%= hermes_operator.network.routing['e212_mnc'] %><br/>
        <% end %>
      </div>
      </td>
      <td><%= link_to 'Destroy', hermes_operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
<h4>Election import</h4>
<h4>Rosi import</h4>
<strong><%= @rosi_total.count %></strong> rows and <strong><%= @rosi_matches.count %></strong> matches, showing matches on top
<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Network</th>
        <th>Rosi id</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @rosi_total) do |rosi_match| %>
      <td><%= rosi_match.network_id %> <% if rosi_match.network_id %>(<%= rosi_match.try(:display_name) %>)<% end %></td>
      <td style="max-width: 200px;">
      <div class="imsi">
        <%= rosi_match.rosi_id %>
      </div>  
      </td>
      <% end %>
    </tbody>
  </table>

app/views/index/index.html.erb
<div id="login-box">
	<%= render 'user_sessions/form' %>
</div>
<div class="splash">

</div>

app/views/index/line_range_code_export.html.erb
<script>
  $(function(){
    $('.tab').click(function(e){
      e.preventDefault();
      $('.tab').removeClass('active')
      $(this).addClass('active');
      $('.content').hide();
    });
    $('.sms-hub').click(function(){
      $('.sms-hub-content').show();
    });
    $('.ir21').click(function(){
      $('.ir21-content').show();
    })
  })
</script>
<% cache(@line_ranges, public: :true) do %>
<br/><br/>
<a href="/ir21/line-range-overview-ir21">
  <div class="btn btn-default">
    IR21 line ranges
  </div>
</a>
<%= link_to line_range_overview_export_path do %>
<div class="btn btn-default">
  Imported line ranges (sms hub)
</div>
<% end %>
<div class="active btn btn-default">
  Code ranges (sms hub)
</div>


<div class="sms-hub-content content">
  <h1>Line range overview (Codes)</h1>
  <br/><br/>
  <table class="table table-striped table-bordered table-hover sortable-ajax" data-query-url= 'get-code-data/query?&page={page}&size={size}&{sortList:sort}&{filterList:filter}'>
    <thead>
      <tr>
        <th>Organisation</th>
        <th>Line range</th>
        <th>Imsi</th>
        <th>Message</th>
        <th>Imported from</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'line_range_code_partial', line_ranges: @line_ranges %>
    </tbody>
  </table>
</div>
<% end %>

app/views/index/line_range_overview_code_ajax_data.js.erb
$('tbody').html("<%=j render("line_range_code_partial", line_ranges: @line_ranges) %>");
var resort = true;
$("table").trigger("update", [resort]);

app/views/index/line_range_overview_ir21.html.erb
<script>
  $(function(){
    $('.tab').click(function(e){
      e.preventDefault();
      $('.tab').removeClass('active')
      $(this).addClass('active');
      $('.content').hide();
    });
    $('.sms-hub').click(function(){
      $('.sms-hub-content').show();
    });
    $('.ir21').click(function(){
      $('.ir21-content').show();
    })
  })
</script>
<% cache(@organisations, public: :true) do %>
<br/><br/>

  <div class="active btn btn-default">
    IR21 line ranges
  </div>

  <%= link_to line_range_overview_export_path do %>
    <div class="btn btn-default">Imported line ranges (sms hub)</div>
  <% end %>



<div class="ir21-content content">
  <h1>Line range overview (IR21)</h1>
  <br/><br/>
  <table class="table table-striped table-bordered table-hover sortable">
    <thead>
      <tr>
        <th>Organisation</th>
        <th>Line range ID</th>
        <th>Start Range</th>
        <th>Stop range</th>
        <th>Network</th>
        <th>Message</th>
      </tr>
    </thead>
    <tbody>
      <% @organisations.each do |organisation| %>
      <% network_ids = Network.where(organisation_id: organisation.id).pluck(:id).to_a %>
      <% line_ranges = NetworkLineRange.order("range_start").joins(:network).where("network_id IN(?)", network_ids).take(20)  %>
      <% line_ranges.each do |range| %>
      <tr>
        <td><%= organisation.name %></td>
        <td><%= range.id %></td>
        <td <% if range.removed == true %> style="color: #EB274B" <% end %>>
          <%= range.range_start %>
        </td>
        <td <% if range.removed == true %> style="color: #EB274B" <% end %>>
          <%= range.range_stop %>
        </td>
        <td><%= range.network.display_name %></td>
        <td>
          <% if range.message %>
          <%= range.message.gsub('overlapping', 'overlapped by').gsub('of', '').gsub('ranges', 'range ID') %>
          <% end %>
        </td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
    <% end %>
  </table>
</div>

app/views/index/mno_ip_overview.html.erb
<h1>Lte Mno</h1>
<table class="table table-striped table-bordered table-hover sortable">
  <thead>
    <tr>
      <th>SMS number administrationID</th>
      <th>Country</th>
      <th>Carrier</th>
      <th>MNO_IP_Range</th>
    </tr>
  </thead>
  <tbody>
    <% @lte_mno_ip.each do |ip| %>
      <tr class="lte-mno-row data-row" data-id="<%= ip.id %>">
        <td class="edit lte-mno" data-type='mno|sms_number_administration_id'>
          <%= ip.sms_number_administration_id %>
        </td>
        <td class="edit lte-mno" data-type='mno|country'>
          <%= ip.country %>
        </td>
        <td class="edit lte-mno" data-type='mno|carrier'>
          <%= ip.carrier %>
        </td>
        <td class="edit lte-mno" data-type='mno|MNO_IP_Range' style="display: block; word-break: break-all;">
          <%= ip.MNO_IP_Range %>
        </td>
        <td>
          <%= link_to delete_mno_ip_line_path(id: ip.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <% end %>
        </td>
      </tr>
    <% end %>
    <%= link_to 'Add line', add_mno_ip_line_path, class: 'add-mno-ip-line' %>
  </tbody>
</table>

<h1>Lte sccp</h1>
<table class="table table-striped table-bordered table-hover sortable">
  <thead>
    <tr class="lte-sccp-row">
      <th>GSMRoSiSCCPprovider_ID</th>
      <th>SCCPproviderName</th>
      <th>SCCP_IP_Range</th>
      <th>Country</th>
      <th>SCCP_Hostname</th>
    </tr>
  </thead>
  <tbody>
    <% @lte_sccp_ip.each do |ip| %>
      <tr class="lte-sccp-row data-row" data-id="<%= ip.id %>">
        <td class="edit lte-sccp" data-id="<%= ip.id %>" data-type='sccp|GSMRoSiSCCPprovider_ID'><%= ip.GSMRoSiSCCPprovider_ID %></td>
        <td class="edit lte-sccp" data-id="<%= ip.id %>" data-type='sccp|SCCP_provider_Name'><%= ip.SCCP_provider_Name %></td>
        <td class="edit lte-sccp" data-id="<%= ip.id %>" data-type='sccp|SCCP_IP_Range' style="display: block; word-break: break-all;"><%= ip.SCCP_IP_Range %></td>
        <td class="edit lte-sccp" data-id="<%= ip.id %>" data-type='sccp|Country'><%= ip.Country %></td>
        <td class="edit lte-sccp" data-id="<%= ip.id %>" data-type='sccp|SCCP_Hostname'><%= ip.SCCP_Hostname %></td>
        <td>
          <%= link_to delete_sccp_ip_line_path(id: ip.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <% end %>
        </td>
      </tr>
    <% end %>
    <%= link_to 'Add line', add_sccp_ip_line_path, class: 'add-sccp-ip-line' %>
  </tbody>
</table>

app/views/index/settings.html.erb
<h1>Settings</h1>
<br/><br/>
<nav>
	<div class="row">
		<div class="col-md-1" style="margin-right: 20px;">
			<%= link_to network_sections_path do %>
			<i class="fa fa-th-list"></i>
			<div class=name>SECTIONS</div>
			<% end %>
		</div>
		<div class="col-md-1" style="margin-right: 20px;">
			<%= link_to import_diff_path do %>
			<i class="fa fa-sort-amount-desc"></i>
			<div class="name">IMPORTS</div>
			<% end %>
		</div>
		<div class="col-md-1">
			<%= link_to "/api/v1/networks" do %>
			<i class="fa fa-exchange"></i>
			<div class="name" style="text-align: center;">API</div>
			<% end %>
		</div>
		<div class="col-md-1">
			<%= link_to flagged_networks_path do  %>
			<i class="fa fa-exclamation-triangle"></i>
			<div class="name">Flagged networks</div>
			<% end %>
		</div>
		<div class="col-md-1">
			<%= link_to users_path do  %>
			<i class="fa fa-user" aria-hidden="true"></i>
			<div class="name">Users</div>
			<% end %>
		</div>

		<div class="col-md-1">
			<%= link_to countries_path do %>
			<i class="fa fa-flag" aria-hidden="true"></i>
			<div class="name">Countries</div>
			<% end %>
		</div>
		<div class="col-md-1">
			<%= link_to notify_groups_path do %>
			<i class="fa fa-users" aria-hidden="true"></i>
			<div class="name">Notify groups</div>
			<% end %>
		</div>

		<div class="col-md-1">
			<%= link_to upload_sms_hub_file_path do %>
			<i class="fa fa-cloud-upload" aria-hidden="true"></i>
			<div class="name">Upload code file</div>
			<% end %>
		</div>

		<div class="col-md-1">
			<%= link_to organisations_path do %>
			<i class="fa fa-globe" aria-hidden="true"></i>
			<div class="name">Organisations</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<%= link_to line_range_overview_export_path do %>
			<i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>
			<div class="name">Line range overview</div>
			<% end %>
		</div>
		<div class="col-md-1">
			<%= link_to mno_ip_overview_path do %>
			<i class="fa fa-phone-square" aria-hidden="true"></i>
			<div class="name">Lte mno/sccp overview</div>
			<% end %>
		</div>
	</div>
	
</nav>

app/views/index/test_mail.html.erb
<h1>test mail</h1>

app/views/index/view_settigns.html.erb
<h1>View Settings</h1>