config/routes.rb
Rails.application.routes.draw do
  get '/' => "index#index"

  scope '/ir21' do
    get 'notification/index'

    resources :countries
    resources :change_histories
    resources :activities
    resources :network_section_fields
    resources :hermes_operators
    resources :organisations
    resources :users
    resources :user_sessions
    resources :network_sections
    resources :reports

    resources :exports do
      collection do
        get 'hermes-csv-export', to: 'exports#hermes_csv_export', as: "hermes_csv_export"
        get 'lte-sccp-ip-csv-export', to: 'exports#lte_sccp_ip_csv_export', format: 'csv'
        get 'lte-mno-ip-csv-export', to: 'exports#lte_mno_ip_csv_export', format: 'csv'
        get 'export-all-networks', to: 'exports#export_all_networks', format: 'xls'
        get 'export-all-networks-xlsx', to: 'exports#export_all_networks_xlsx', format: 'xlsx'
        get 'advanced-network-export', to: 'exports#export_all_networks_advanced', format: 'csv'
        get 'export-telenor-connexion', to: 'exports#export_telenor_connexion', format: 'xls'
        get 'generate-codes', to: 'exports#generate_codes', as: :generate_codes, format: 'csv'
        get 'generate-single-codes', to: 'exports#generate_single_codes', as: :generate_single_codes, format: 'xlsx'
        get 'sor-export', to: 'exports#sor_export', as: :sor_export, format: 'csv'
        get 'advanced-sor-export', to: 'exports#advanced_sor_export', as: :advanced_sor_export, format: 'csv'
        get 'sccp-ip-export', to: 'export#sccp_ip_export', as: :sccp_ip_export, format: 'csv'
      end
    end

    resources :imports do
      get 'resolve-conflict', to: "imports#resolve_conflict", as: "resolve-conflict"
      put 'link-pdf', to: 'imports#link_pdf', as: 'link_pdf'
      put 'mark-pdf-networks', to: 'imports#mark_pdf_networks', as: 'mark_pdf_networks'
      put 'unlink-pdf', to: 'imports#unlink_pdf', as: 'unlink_pdf'
      get 'resolve', to: 'imports#resolve', as: :resolve
      collection do
        get 'summery', to: 'imports#summery', as: 'summery'
      end
    end

    resources :networks do
      resources :versions
      get 'read-xml', to: "networks#read_xml", as: "read-xml"
      get 'read-excel', to: "networks#read_excel", as: "read-excel"
    end

    api_version(:module => "api/v1", :path => {:value => "api/v1"}, defaults: {format: 'json'}) do
      resources :organisations do
        collection do 
          get 'mulesoft', to: 'organisations#mulesoft', as: :mulesoft
          get 'line-ranges', to: 'organisations#line_ranges', as: :line_ranges
        end  
      end
      resources :networks
    end

    # Api for connexion
    api_version(:module => "api/v1/connexion", :path => {:value => "api/v1/connexion"}, defaults: {format: 'json'}) do
      resources :organisations do
        resources :networks
        collection do
          get 'all-network-details', to: 'networks#all_network_details'
        end
      end
    end

    root 'index#index'
    get 'read-pdf', to: "networks#read_pdf", as: "read-pdf"
    match 'search', to: 'search#index', as: 'search', via: [:POST,:GET]
    get 'sign-in', to: 'user_sessions#new', as: 'sign-in'
    get 'sign-out', to: 'user_sessions#destroy', as: 'sign-out'
    get 'revert/:id', to: 'versions#revert', as: 'revert'
    get 'forgot-password', to: 'users#forgot_password', as: 'forgot_password'
    put 'networks/:id/update_hstore_field', to: 'networks#update_hstore_field', as: 'network_update_hstore'
    put 'networks/:id/update_network_field', to: 'networks#update_network_field', as: 'network_update'
    put 'networks/:id/update_hstore_section_field', to: 'networks#update_hstore_section_field', as: 'network_section_update_hstore'
    put 'networks/:id/update_network_index_field', to: 'networks#update_network_index_field', as: 'network_update_index'
    get 'delete-row/:id', to: 'networks#delete_row'
    get 'active-imports', to: 'imports#active_imports', as: 'active-imports'
    get 'settings', to: 'index#settings', as: 'settings'
    get 'change-password', to: 'users#change_password', as: 'change_password'
    post 'send-reset-password', to: 'users#send_reset_password', as: 'reset_password'
    get 'run-rake-import', to: 'imports#run_import', as: 'run_rake_import'
    match 'remote-login', to: 'user_sessions#remote_login', via: [:POST,:GET]
    put 'network-section-update-field', to: 'network_section_fields#update_field'
    get 'soap-test', to: 'imports#soap_test', as: 'soap-test'
    get 'import-diff', to: 'index#import_diffs', as: 'import_diff'
    get 'flagged-networks', to: 'networks#flagged_networks', as: 'flagged_networks'
    get 'import-files', to: 'imports#import_files', as: 'import_files'
    get 'read-file/:id', to: 'imports#read_file', as: 'read_file'
    get 'show-diff-snapshot/:id', to: 'networks#show_diff_snapshot', as: 'show_diff_snapshot'
    post 'add-line-range', to: 'networks#add_line_range', as: 'add_line_range'
    put 'edit-linerange', to: 'networks#edit_linerange',as: 'edit-line-range', format: 'js'
    delete 'delete-line-range/:id', to: 'networks#delete_line_range', as: 'delete_line_range'
    get 'notifications', to: 'notification#index', as: :notifications
    match 'add-role', to: 'users#add_role', as: :add_role, via: [:POST,:GET]
    get 'delete-role', to: 'users#remove_role', as: :delete_role
    get 'download-export', to: 'exports#download_export', as: :download_export
    get 'notify-groups', to: "notification#notify_groups", as: :notify_groups
    get 'notify-group/:id', to: "notification#notify_group", as: :notify_group
    post 'add-notify-group-profile', to: "notification#add_profile", as: :add_notify_group_profile
    get 'show-notify-networks', to: 'notification#show_networks', as: :show_notify_networks, format: 'js'
    post 'add-notify-group-network', to: "notification#add_network", as: :add_notify_group_network
    post 'add-notify-group-organisation', to: 'notification#add_organisation', as: :add_notify_group_organisation
    match 'lazy-load-line-ranges', to: 'networks#lazy_load_line_ranges', as: :lazy_load_line_ranges, via: [:POST, :GET, :PUT]
    match 'lazy-load-network-sections', to: 'networks#lazy_load_network_sections', as: :lazy_load_network_sections, via: [:POST, :GET, :PUT]
    delete 'delete-notify-group/:id', to: 'notification#delete_notify_group', as: :delete_notify_group
    get 'add_notify_group_to_user', to: 'notification#add_notify_group_to_user', as: :add_notify_group_to_user
    get 'activate-all-imports', to: 'imports#activate_all_imports', as: :activate_all_imports
    delete 'delete-network-from-notify-group', to: 'networks#delete_from_notify_group', as: :delete_network_from_notify_group
    delete 'delete-organisation-from-notify-group', to: 'organistions#delete_from_notify_group', as: :delete_organisation_from_notify_group
    delete 'delete-notify-group-from-user', to: 'users#delete_from_notify_group', as: :delete_from_notify_group
    get 'show-network-comment', to: 'networks#show_network_comment', as: :show_network_comment, defaults: {format: 'js'}
    match 'add-notify-setting-to-user', to: 'notification#add_notify_setting_to_user', as: :add_notify_setting_to_user, defaults: {format: 'js'}, via: [:POST,:GET]
    match 'remove-notify-setting-from-user', to: 'notification#remove_notify_setting_from_user', as: :remove_notify_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET] 
    match 'add-view-setting-to-user', to: 'users#add_view_setting_to_user', as: :add_view_setting_to_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'remove-view-setting-from-user', to: 'users#remove_view_setting_from_user', as: :remove_view_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'upload-sms-hub-file', to: 'imports#upload_sms_hub_file', as: :upload_sms_hub_file, via: [:POST, :GET]
    match 'customized-exports', to: 'exports#customized_exports', as: :customized_exports, via: [:POST, :GET]
    get 'create-manual-export', to: 'exports#create_manual_export', as: :create_manual_export
    get 'view-settings', to: 'index#view_settings', as: :view_settings
    get 'show-sms-hub-data', to: 'index#show_sms_hub_data', as: :show_sms_hub_data
    get 'get-rest-of-networks', to: 'networks#get_rest_of_networks', as: :get_rest_of_networks
    get 'get-rest-of-networks-dynamic/:id', to: 'networks#get_rest_of_networks_dynamic', as: :get_rest_of_networks_dynamic
    match 'export-ip-addresses', to: 'exports#export_ip_addresses', as: :export_ip_addresses, via: [:POST, :GET]
    get 'line-range-overview-ir21', to: 'index#line_range_overview_ir21', as: :line_range_overview_ir21
    get 'line-range-overview-export', to: 'index#line_range_overview_export', as: :line_range_overview_export
    get 'line-range-code-export', to: 'index#line_range_code_export', as: :line_range_code_export
    get 'import-details/:id', to: 'imports#import_details', as: :import_details
    get 'create-missing-structutre', to: 'imports#create_missing_structure', as: :create_missing_structure
    post 'get-sms-hub-data', to: 'index#line_range_overview_export_ajax_data', as: :line_range_overview_export_ajax_data, format: :js 
    post 'get-code-data', to: 'index#line_range_overview_code_ajax_data', as: :line_range_overview_code_ajax_data, format: 'js' 
    patch 'change-network-status', to: 'networks#change_network_status', as: :change_network_status
    get 'mno-ip-overview', to: 'index#mno_ip_overview', as: :mno_ip_overview
    post 'update-mno-sccp-ip', to: 'index#update_mno_sccp_ip', as: :update_mno_sccp_ip
    get 'add-mno-ip-line', to: 'index#add_mno_ip_line', as: :add_mno_ip_line
    get 'add-sccp-ip-line', to: 'index#add_sccp_ip_line', as: :add_sccp_ip_line
  end


##### PLAIN ROUTE SECTION ########################################
# Theese extra route exist to render proxy correct
# It makes it possible to each render /ir21 scope and plain url´s
#
###################################################################

app/views/imports/_archived_imports.html.erb
<% @archived_imports = Import.where(archive: true, removed: false).order("created_at DESC").take(100) %>
<% @archived_imports.each do |import| %>
  <tr>
    <td><%= import.file_name %>
      <% case import.file_type %>
      <% when 'xml' %>
        <% if import.network %>
          <%= link_to network_read_xml_path(import.network) do %>
            <i class='fa fa-file-code-o'></i>
          <% end %> |
          <%= link_to import.network.display_name, import.network %>
        <% else %>
          <i class='fa fa-file-code-o'></i>
        <% end %>
      <% when 'pdf' %>
        <% unless import.pdfs.blank? %> 
          <%= link_to read_pdf_path(pdf_id: import.pdfs.first.id),data: {turbolinks: false} do %>
            <i class='fa fa-file-pdf-o'></i>
          <% end %>
          <span class="network_name linked" data-pdf-id="<%= import.id %>" data-toggle="modal" data-target="#pdfmodal"> | <%= import.organisation.try(:name) %> - linked to <%= pluralize(import.pdfs.last.pdf_networks.count, 'network') %> </span>   
        <% else %>
          <% if import.network %> 
          <%= link_to read_pdf_path(import: import) do %>
            <i class='fa fa-file-pdf-o'></i>
          <% end %>
          <span class="network_name"> | <%= link_to Network.find(import.network_id).display_name, Network.find(import.network_id) %></span>
            <%= link_to import_unlink_pdf_path(import.id) do %>
              <span class="linked" data-toggle="modal" data-pdf-id="<%= import.id %>">(Unlink)</span>
            <% end %>   
        <% else %>
        <i class='fa fa-file-pdf-o'></i>
          <span class="not-linked" data-toggle="modal" data-pdf-id="<%= import.id %>" data-target="#pdfmodal">
            Not linked
          </span>
        <% end %>
        <% end %>
      <% when 'xlsx', 'xls' %>
        <% if import.network %>
          <%= link_to network_read_excel_path(import.network) do %>
            <i class="fa fa-file-excel-o"></i>
          <% end %> |
          <%= link_to import.network.display_name, import.network %>
        <% else %>
          <i class="fa fa-file-excel-o"></i>
        <% end %>
        </td>
        </tr>
      <% end %>
<% end %>

app/views/imports/_error_notice_modal.html.erb
<div class="modal fade" id="errormodal">
  <div class="modal-dialog" style="width: auto; max-width: 1300px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Errors in imports</h4>
      </div>
      <div class="modal-body">
        <table class="table-responsive table-striped sortable">
          <thead>
            <tr>
              <td>File Name</td>
              <td>Message</td>
              <td>Resolve</td>
            </tr>
          </thead>
          <tbody>
          <% @failed_imports.each do |import| %> 
            <tr>
              <td>
                <%= import.original_filename %>
              </td>
              <td>
                <%= import.error_message %>
              </td>
              <td style="width: 200px;">
                <div style="width: 400px;">
                  <% if import.error_message == 'Import is trying to create a new organisation' %>
                  <strong>Use one of theese organisations</strong><br/> 
                  <% import.organisation_override.each do |org| %>
                  <%= link_to import_resolve_path(import, organisation_override: org) do %>
                  <%= Organisation.find(org).name %> - <%= Organisation.find(org).networks.count %> connected networks <br/>
                  <% end %>
                  <% end %>
                  <% if import.organisation_override.blank? %>
                    No previous Organisations found
                  <% end %>
                  <br/>
                  <strong>Or</strong><br/> 
                  <%= link_to import_resolve_path(import) do %>
                  Create a new organisation
                  <% end %>
                  <% else %>
                    Contact technical support
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="clearfix"></div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/imports/_form.html.erb
<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="myLabel">
    <%= f.file_field :file_name, multiple: true, name: "import[file_name]", class: "custom-file-input"  %>
    <span>Add new file</span>
  </div>
<% end %>

app/views/imports/_pdf_linking_modal.html.erb
<div class="modal fade" id="pdfmodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Choose network to link</h4>
      </div>
      <div class="modal-body">
        <table class="table-responsive table-striped sortable">
          <thead>
            <tr>
              <th>
                Organisation
              </th>
              <th>
                Network
              </th>
              <th>
                Mnc
              </th>
              <th>
                Mcc
              </th>
            </tr>
          </thead>
          <tbody>
            <% Network.joins(:organisation).includes(:pdf_networks).order("organisations.name, networks.display_name").all.each do |network| %>
            <tr data-organisation-id="<%= network.try(:organisation).id %>" data-network-id="<%= network.id %>" class="<% if network.pdf_networks.blank? %>choose-network<% else %>choosen<% end %>" id="network_<%= network.id %>">
              <td id="organisation_<%= network.try(:organisation).id %>" class="organisation">
                <%= network.try(:organisation).try(:name) %>
              </td>
              <td class="network_<%= network.id %> network">
                <%= network.display_name %>
              </td>
              <td class="network">
                <%= network.routing.try(:[], "e212_mcc") %>
              </td>
              <td class="network">
                <%= network.routing.try(:[], "e212_mnc") %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="clearfix"></div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/imports/create.js.erb
<% if @import_check %>
	alert("<%= @import.original_filename %> has been successfully uploaded before")
<% end %>
if(!$('.drop-area').hasClass("marked")) {
	$('.drop-area').show().html('').addClass('marked');
}
$('.drop-here').remove();
if("<%= @import.file_type %>" == "xml"){
  $('.drop-area').append('<i class="fa fa-times delete" aria-hidden="true" data-import-id="<%= @import.id %>"></i><i class="fa fa-file-code-o" data-toggle="tooltip" title="<%= @import.file_name %>"></i>');
}
if("<%= @import.file_type %>" == "pdf"){
  $('.drop-area').append('<i class="fa fa-times delete" aria-hidden="true" data-import-id="<%= @import.id %>"></i><i class="fa fa-file-pdf-o" data-toggle="tooltip" title="<%= @import.file_name %>"></i>');
}
if("<%= @import.file_type %>" == "xlsx"){
  $('.drop-area').append('<i class="fa fa-times delete" aria-hidden="true" data-import-id="<%= @import.id %>"></i><i class="fa fa-file-excel-o" data-toggle="tooltip" title="<%= @import.file_name %>"></i>');
}
if("<%= @import.file_type %>" == "xls"){
  $('.drop-area').append('<i class="fa fa-times delete" aria-hidden="true" data-import-id="<%= @import.id %>"></i><i class="fa fa-file-excel-o" data-toggle="tooltip" title="<%= @import.file_name %>"></i>');
}
$('#done').show();

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/import_files.html.erb
<script>
	$(function(){
		$('.date').datepicker({
			format: 'yyyy-mm-dd'
		});
	})

</script>
<% cache(@files, public: :true) do %>
<h1>Import files</h1>
<div class="page-header">
	<%= form_tag("/ir21/import-files?network_id=params[:network_id]",method: :get) do %>
	<%= text_field_tag :start_date, params[:start_date], placeholder: "Start date", data: {provide: 'datepicker'}, class: "date" %> - 
	<%= text_field_tag :stop_date, params[:stop_date], placeholder: "Stop date", data: {provide: 'datepicker'}, class: "date" %>
	<%= submit_tag "Show" %>
	<% end %>
</div>
<table class="table-responsive table-striped">
	<thead style="white-space: nowrap;">
		<tr>
			<th>Filename</th>
			<th>Filetype</th>
			<th>Import date</th>
			<th>File creation date</th>
			<th>Country</th>
			<th>Linked to network</th>
			<% if current_user.has_any_role? :admin, :superadmin %>
			<th>Delete</th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% @files.each do |file| %>
		<tr>
			<td>		
				<%= link_to file.file_name.truncate(50), read_file_path(file), data: {turbolinks: :false	} %>
			</td>
			<td>
				<% case file.file_type %>
				<% when "xlsx"
				"excel file"	 %>
				<% end %>
				<%= file.file_type %>
			</td>
			<td>
				<%= file.created_at.to_date %>
			</td>
			<td>
				<%= file.try(:file_creation_date).try(:to_date) %>	
			</td>
			<td>
				<%= file.network.try(:country).try(:name) %></td>
				<td>
					<% if file.network %>
					<%= link_to file.network.display_name, file.network if file.network %>
					<% else %>
					<% if file.file_type == 'pdf' && @network %>
					<%= link_to @network.display_name, @network %>
					<% end %>
					<!-- Try to find network through import reference in networks -->
					<%= link_to Network.where(import_id: file.id).first.try(:display_name), Network.where(import_id: file.id).first if  Network.where(import_id: file.id).first %> 
					<% end %>
					<% if current_user.has_any_role? :admin, :superadmin %>
					<td>
						<%= link_to 'Destroy', file, method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>

app/views/imports/resolve_conflict.html.erb
<h1>Resolve conflict</h1>
<% @conflicts.each do |conflict| %>
    <% next unless conflict %>
    <div>
      <div class="date">
        <%= conflict.created_at.to_date %>
      </div>
      <div class="creator">
        By: <%= User.find_by(id: conflict.whodunnit).try(:fullname) %>
      </div>
    </div>
    <% if conflict.object_changes %>
        <% split = conflict.object_changes.split("-") %>
        <% string1 = split[4].to_s %>
        <% string2 = split[5].to_s %>
        <h3>Changes</h3>
        <div class="change">
          <%
             s1 = string1.split('\'')
             s2 = string2.split('\'')
          %>
          <% after = s2 - s1 %>
          <% before = s1 - s2 %>
          <% key = s2.find { |x| x } %>

          <h4>From XML</h4>

          <div class="before">
            <%= key.humanize %> <span class="change-value"><%= before.first %></span>
          </div>

          <h4>User updated</h4>

          <div class="after">
            <%= key.humanize %> <span class="change-value"><%= after.first %></span>
          </div>
        </div>
        <div class="change-buttons">
          <div class="use-xml">Use xml version</div>
          <div class="use-updated">Use updated version</div>
        </div>
        <div class="clearfix"></div>
        <br/><br/>
    <% end %>
<% end %>

app/views/imports/scrape_test.html.erb
<h1>Scraping</h1>
<%= debug @submit %>

app/views/imports/scraping_settings.html.erb
<h1>Scraping settings</h1>

<%= bootstrap_form_for(@scraping_settings, url: {action: 'update_scrapings'}) do |f| %>
  <% if @scraping_settings.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scraping_settings.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @scraping_settings.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Provide a new password" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "update scraping settings" %>
  </div>
<% end %>

app/views/imports/show.html.erb
<br/><br/>
<p>
	<strong>File name:</strong>
	<%= @import.file_name %>
	<% if @import.network %>
	<%= link_to network_read_xml_path(@import.network) do %>
	<% end %>
	<%= link_to network_read_xml_path(@import.network) do %>
	<i class="fa fa-file-excel-o"></i>
	<% end %>
	<% end %>
</p>
<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/imports/soap_test.html.erb
<h1>SOAP - SMS - HUB</h1>
<%= debug @body %>

app/views/imports/summery.html.erb
<script>
  $(function(){
    $('.date').datepicker({
      format: 'yyyy-mm-dd'
    });
  })

</script>

<% cache(@imports, public: :true) do %>
<h1>Import Summery</h1>
<div class="page-header">
  <%= form_tag("/ir21/imports/summery",method: :get) do %>
  <%= text_field_tag :start_date, params[:start_date], placeholder: "Start date", data: {provide: 'datepicker'}, class: "date" %> - 
  <%= text_field_tag :stop_date, params[:stop_date], placeholder: "Stop date", data: {provide: 'datepicker'}, class: "date" %>
  <%= submit_tag "Show" %>
  <% end %>
</div>
<table class="table-responsive table-striped networks sortable">
	<thead style="white-space: nowrap;">
		<tr>
			<th>Date</th>
			<th>Network</th>
			<th>Tadig</th>
			<th>File</th>
			<th>Effective date of change</th>
			<th>Changed sections</th>
		</tr>
	</thead>
	<tbody>
		<% @imports.each do |import| %>
			<tr>
				<td><%= import.created_at.to_date %></td>
				<td><%= import.network.try(:display_name) %></td>
				<td><%= import.network.try(:tadig_code) %></td>
				<td>
      <% case import.file_type %>
      <% when 'xml' %>
        <% if import.network %>
          <%= link_to network_read_xml_path(import.network) do %>
            <i class='fa fa-file-code-o'></i>
          <% end %> |
          <%= link_to import.network.display_name, import.network %>
        <% else %>
          <i class='fa fa-file-code-o'></i>
        <% end %>
      <% when 'pdf' %>
        <% if import.network %> 
          <%= link_to read_pdf_path(import: import) do %>
            <i class='fa fa-file-pdf-o'></i>
          <% end %>
          <span class="network_name"> | <%= link_to Network.find(import.network_id).display_name, Network.find(import.network_id) %></span>
            <%= link_to import_unlink_pdf_path(import.id) do %>
              <span class="linked" data-toggle="modal" data-pdf-id="<%= import.id %>">(Unlink)</span>
            <% end %>   
        <% else %>
        <i class='fa fa-file-pdf-o'></i>
          <span class="not-linked" data-toggle="modal" data-pdf-id="<%= import.id %>" data-target="#pdfmodal">
            Not linked
          </span>
        <% end %>
      <% when 'xlsx', 'xls' %>
        <% if import.network %>
          <%= link_to network_read_excel_path(import.network) do %>
            <i class="fa fa-file-excel-o"></i>
          <% end %> |
          <%= link_to import.network.display_name, import.network %>
        <% else %>
          <i class="fa fa-file-excel-o"></i>
        <% end %>
      <% end %>
      </td>
				<td>
        <% if import.network %>
          <%= import.network.routing["effective_date_of_change"] %>
        <% end %>
        </td>
				<td>
					<% if import.try(:network_diffs) %>
						<% import.network_diffs.each do |diff| %>
							<%= link_to show_diff_snapshot_path(diff.id) do %>
                <%= diff.message %>
              <% end %>
						<% end %>
					<% else %>
						no changes
					<% end %>
				</td>
			</tr>
		<% end %> 		
	</tbody>
</table>
<% end %>

app/views/imports/upload_sms_hub_file.html.erb
<h1>Upload Code file</h1>

<%= form_tag({controller: "imports", action: "upload_sms_hub_file"},multipart: true) do %>
<br/><br/>
<%= file_field_tag "file" %>
<br/><br/>
<%= submit_tag "Upload file" %>
<% end %>