config/routes.rb
Rails.application.routes.draw do
  get '/' => "index#index"

  scope '/ir21' do
    get 'notification/index'

    resources :countries
    resources :change_histories
    resources :activities
    resources :network_section_fields
    resources :hermes_operators
    resources :organisations
    resources :users
    resources :user_sessions
    resources :network_sections
    resources :reports

    resources :exports do
      collection do
        get 'hermes-csv-export', to: 'exports#hermes_csv_export', as: "hermes_csv_export"
        get 'lte-sccp-ip-csv-export', to: 'exports#lte_sccp_ip_csv_export', format: 'csv'
        get 'lte-mno-ip-csv-export', to: 'exports#lte_mno_ip_csv_export', format: 'csv'
        get 'export-all-networks', to: 'exports#export_all_networks', format: 'xls'
        get 'export-all-networks-xlsx', to: 'exports#export_all_networks_xlsx', format: 'xlsx'
        get 'advanced-network-export', to: 'exports#export_all_networks_advanced', format: 'csv'
        get 'export-telenor-connexion', to: 'exports#export_telenor_connexion', format: 'xls'
        get 'generate-codes', to: 'exports#generate_codes', as: :generate_codes, format: 'csv'
        get 'generate-single-codes', to: 'exports#generate_single_codes', as: :generate_single_codes, format: 'xlsx'
        get 'sor-export', to: 'exports#sor_export', as: :sor_export, format: 'csv'
        get 'advanced-sor-export', to: 'exports#advanced_sor_export', as: :advanced_sor_export, format: 'csv'
        get 'sccp-ip-export', to: 'export#sccp_ip_export', as: :sccp_ip_export, format: 'csv'
      end
    end

    resources :imports do
      get 'resolve-conflict', to: "imports#resolve_conflict", as: "resolve-conflict"
      put 'link-pdf', to: 'imports#link_pdf', as: 'link_pdf'
      put 'mark-pdf-networks', to: 'imports#mark_pdf_networks', as: 'mark_pdf_networks'
      put 'unlink-pdf', to: 'imports#unlink_pdf', as: 'unlink_pdf'
      get 'resolve', to: 'imports#resolve', as: :resolve
      collection do
        get 'summery', to: 'imports#summery', as: 'summery'
      end
    end

    resources :networks do
      resources :versions
      get 'read-xml', to: "networks#read_xml", as: "read-xml"
      get 'read-excel', to: "networks#read_excel", as: "read-excel"
    end

    api_version(:module => "api/v1", :path => {:value => "api/v1"}, defaults: {format: 'json'}) do
      resources :organisations do
        collection do 
          get 'mulesoft', to: 'organisations#mulesoft', as: :mulesoft
          get 'line-ranges', to: 'organisations#line_ranges', as: :line_ranges
        end  
      end
      resources :networks
    end

    # Api for connexion
    api_version(:module => "api/v1/connexion", :path => {:value => "api/v1/connexion"}, defaults: {format: 'json'}) do
      resources :organisations do
        resources :networks
        collection do
          get 'all-network-details', to: 'networks#all_network_details'
        end
      end
    end

    root 'index#index'
    get 'read-pdf', to: "networks#read_pdf", as: "read-pdf"
    match 'search', to: 'search#index', as: 'search', via: [:POST,:GET]
    get 'sign-in', to: 'user_sessions#new', as: 'sign-in'
    get 'sign-out', to: 'user_sessions#destroy', as: 'sign-out'
    get 'revert/:id', to: 'versions#revert', as: 'revert'
    get 'forgot-password', to: 'users#forgot_password', as: 'forgot_password'
    put 'networks/:id/update_hstore_field', to: 'networks#update_hstore_field', as: 'network_update_hstore'
    put 'networks/:id/update_network_field', to: 'networks#update_network_field', as: 'network_update'
    put 'networks/:id/update_hstore_section_field', to: 'networks#update_hstore_section_field', as: 'network_section_update_hstore'
    put 'networks/:id/update_network_index_field', to: 'networks#update_network_index_field', as: 'network_update_index'
    get 'delete-row/:id', to: 'networks#delete_row'
    get 'active-imports', to: 'imports#active_imports', as: 'active-imports'
    get 'settings', to: 'index#settings', as: 'settings'
    get 'change-password', to: 'users#change_password', as: 'change_password'
    post 'send-reset-password', to: 'users#send_reset_password', as: 'reset_password'
    get 'run-rake-import', to: 'imports#run_import', as: 'run_rake_import'
    match 'remote-login', to: 'user_sessions#remote_login', via: [:POST,:GET]
    put 'network-section-update-field', to: 'network_section_fields#update_field'
    get 'soap-test', to: 'imports#soap_test', as: 'soap-test'
    get 'import-diff', to: 'index#import_diffs', as: 'import_diff'
    get 'flagged-networks', to: 'networks#flagged_networks', as: 'flagged_networks'
    get 'import-files', to: 'imports#import_files', as: 'import_files'
    get 'read-file/:id', to: 'imports#read_file', as: 'read_file'
    get 'show-diff-snapshot/:id', to: 'networks#show_diff_snapshot', as: 'show_diff_snapshot'
    post 'add-line-range', to: 'networks#add_line_range', as: 'add_line_range'
    put 'edit-linerange', to: 'networks#edit_linerange',as: 'edit-line-range', format: 'js'
    delete 'delete-line-range/:id', to: 'networks#delete_line_range', as: 'delete_line_range'
    get 'notifications', to: 'notification#index', as: :notifications
    match 'add-role', to: 'users#add_role', as: :add_role, via: [:POST,:GET]
    get 'delete-role', to: 'users#remove_role', as: :delete_role
    get 'download-export', to: 'exports#download_export', as: :download_export
    get 'notify-groups', to: "notification#notify_groups", as: :notify_groups
    get 'notify-group/:id', to: "notification#notify_group", as: :notify_group
    post 'add-notify-group-profile', to: "notification#add_profile", as: :add_notify_group_profile
    get 'show-notify-networks', to: 'notification#show_networks', as: :show_notify_networks, format: 'js'
    post 'add-notify-group-network', to: "notification#add_network", as: :add_notify_group_network
    post 'add-notify-group-organisation', to: 'notification#add_organisation', as: :add_notify_group_organisation
    match 'lazy-load-line-ranges', to: 'networks#lazy_load_line_ranges', as: :lazy_load_line_ranges, via: [:POST, :GET, :PUT]
    match 'lazy-load-network-sections', to: 'networks#lazy_load_network_sections', as: :lazy_load_network_sections, via: [:POST, :GET, :PUT]
    delete 'delete-notify-group/:id', to: 'notification#delete_notify_group', as: :delete_notify_group
    get 'add_notify_group_to_user', to: 'notification#add_notify_group_to_user', as: :add_notify_group_to_user
    get 'activate-all-imports', to: 'imports#activate_all_imports', as: :activate_all_imports
    delete 'delete-network-from-notify-group', to: 'networks#delete_from_notify_group', as: :delete_network_from_notify_group
    delete 'delete-organisation-from-notify-group', to: 'organistions#delete_from_notify_group', as: :delete_organisation_from_notify_group
    delete 'delete-notify-group-from-user', to: 'users#delete_from_notify_group', as: :delete_from_notify_group
    get 'show-network-comment', to: 'networks#show_network_comment', as: :show_network_comment, defaults: {format: 'js'}
    match 'add-notify-setting-to-user', to: 'notification#add_notify_setting_to_user', as: :add_notify_setting_to_user, defaults: {format: 'js'}, via: [:POST,:GET]
    match 'remove-notify-setting-from-user', to: 'notification#remove_notify_setting_from_user', as: :remove_notify_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET] 
    match 'add-view-setting-to-user', to: 'users#add_view_setting_to_user', as: :add_view_setting_to_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'remove-view-setting-from-user', to: 'users#remove_view_setting_from_user', as: :remove_view_setting_from_user, defaults: {format: 'js'}, via: [:POST, :GET]
    match 'upload-sms-hub-file', to: 'imports#upload_sms_hub_file', as: :upload_sms_hub_file, via: [:POST, :GET]
    match 'customized-exports', to: 'exports#customized_exports', as: :customized_exports, via: [:POST, :GET]
    get 'create-manual-export', to: 'exports#create_manual_export', as: :create_manual_export
    get 'view-settings', to: 'index#view_settings', as: :view_settings
    get 'show-sms-hub-data', to: 'index#show_sms_hub_data', as: :show_sms_hub_data
    get 'get-rest-of-networks', to: 'networks#get_rest_of_networks', as: :get_rest_of_networks
    get 'get-rest-of-networks-dynamic/:id', to: 'networks#get_rest_of_networks_dynamic', as: :get_rest_of_networks_dynamic
    match 'export-ip-addresses', to: 'exports#export_ip_addresses', as: :export_ip_addresses, via: [:POST, :GET]
    get 'line-range-overview-ir21', to: 'index#line_range_overview_ir21', as: :line_range_overview_ir21
    get 'line-range-overview-export', to: 'index#line_range_overview_export', as: :line_range_overview_export
    get 'line-range-code-export', to: 'index#line_range_code_export', as: :line_range_code_export
    get 'import-details/:id', to: 'imports#import_details', as: :import_details
    get 'create-missing-structutre', to: 'imports#create_missing_structure', as: :create_missing_structure
    post 'get-sms-hub-data', to: 'index#line_range_overview_export_ajax_data', as: :line_range_overview_export_ajax_data, format: :js 
    post 'get-code-data', to: 'index#line_range_overview_code_ajax_data', as: :line_range_overview_code_ajax_data, format: 'js' 
    patch 'change-network-status', to: 'networks#change_network_status', as: :change_network_status
    get 'mno-ip-overview', to: 'index#mno_ip_overview', as: :mno_ip_overview
    post 'update-mno-sccp-ip', to: 'index#update_mno_sccp_ip', as: :update_mno_sccp_ip
    get 'add-mno-ip-line', to: 'index#add_mno_ip_line', as: :add_mno_ip_line
    get 'add-sccp-ip-line', to: 'index#add_sccp_ip_line', as: :add_sccp_ip_line
  end


##### PLAIN ROUTE SECTION ########################################
# Theese extra route exist to render proxy correct
# It makes it possible to each render /ir21 scope and plain url´s
#
###################################################################

app/models/export_type.rb
class ExportType < ActiveRecord::Base
	has_many :exports
end

app/views/exports/_export_type_modal.html.erb
<div class="modal fade" id="export-type-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Select export type</h4>
      </div>
      <div class="modal-body">
        <h4>Automatic exports</h4>
        <div class="automatic-exports">
          <% @export_types.each do |e| %>
          <%= link_to("#{e.function_call}", protocol: :https) do %>
          <div class="export-row">
            <h5 class="title"><%= e.name %></h5>
            <div class="description">
              <%= e.description %>
            </div>
          </div>
          <% end %>
          <% end %>
          <!-- List automatic but non editable exports -->
          <%= link_to(export_ip_addresses_path) do %>
          <div class="export-row">
            <h5 class="title">Ip address export</h5>
          <% end %>  
            <div class="description">
              Export either Ip address list, Asn list or Grx provider list
            </div>  
          </div>
          
        </div>

        <hr/>
        <h4>Manual exports</h4>
        
        <% @personal_exports.each do |export| %>
        <%= link_to export.name, create_manual_export_path(personal_export_id: export.id) %> 
        <i class="fa fa-times" aria-hidden="true" style="color: #de0029"></i>
        <br/>
        <% end %>
        <div class="manual-exports">
          <%= link_to 'Create a manual export', customized_exports_path, class: 'btn-primary btn' %>
        </div>

        <div class="clearfix"></div>

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/exports/_form.html.erb
<%= form_for(@export, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @export.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@export.errors.count, "error") %> prohibited this export from being saved:</h4>

      <ul>
      <% @export.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :file, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :file, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/exports/create_manual_export.html.erb
<% @personal_export.personal_export_fields.each do |a| %>
  <%= a.export_field.name %>
<% end %>
<%= map = @personal_export.personal_export_fields.map {|d| d.export_field.name} %>
<%= map %>
<%= map.include?("organisation") %>

app/views/exports/customized_exports.html.erb
<h3>Customized IR21 export</h3><br/><br/>
<%= form_tag do %>
<%= text_field_tag "name", nil, placeholder: 'Name of export' %><br/><br/>
<% @fields.each do |field| %>
<%= check_box_tag "main_fields[#{field.id}]"%>
<%= field.name %><br/>

<% end %>
<br/><br/>
<%= submit_tag %>
<% end %>

app/views/exports/edit.html.erb
<div class="page-header">
  <%= link_to exports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @export, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing export</h1>
</div>

<%= render 'form' %>

app/views/exports/export_ip_addresses.html.erb
<h1>Export ip addresses</h1>
<div class="choices">
	<br/>
	<div class="message">Choose ip address section </div>
	<div class="btn-group">
		<button class="choice btn btn-default" data-exporttype="ip">
			Ip address list
		</button>
		<button class="choice btn btn-default" data-exporttype="asn">
			Asn list
		</button>
		<button class="choice btn btn-default" data-exporttype="grx">
			Grx provider list
		</button>
	</div>
</div>
<br/><br/><br/>
	<button class="btn btn-default link">
		Create export
	</button>

app/views/exports/index.html.erb
<% unless @exports_in_progress.blank? %>
<script>
  setInterval(function() {
    window.location.reload();
  }, 25000); 
</script>
<% end %>
<div class="page-header">
  <a href="#" class='btn btn-primary' data-toggle="modal" data-target="#export-type-modal" >
    <span class="glyphicon glyphicon-plus"></span>
    New Export
  </a>
  <h1>Listing exports</h1>
</div>

<% unless @exports_in_progress.blank? %>
<h4>In progress</h4>
<% end %>

<% @exports_in_progress.each do |export| %>
<div class="in_progress">
  <strong><%= export.export_type.name %> <span style="color:#5D9FF3"><%= export.progress %></span></strong>
  - <span style="color: #8C8C8C"> <%= export.created_at.to_date %> <%= export.created_at.to_time.strftime('%H') %>:<%= export.created_at.to_time.strftime('%M') %> </span>
</div>
<% end %>
<% unless @exports_in_progress.blank? %>
<hr/>
<% end %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>File</th>
        <th>User</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @exports) do |export| %>
      <td>
        <%= export.file %>
      </td>
      <td>
        <%= export.user_id %>
      </td>
      <td><%= link_to 'Download', download_export_path(export_id: export), data: {turbolinks: :false} %></td>
      <td><%= link_to 'Destroy', export, method: :delete, data: { confirm: 'Are you sure?', turbolinks: false } %></td>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Export type modal -->
<%= render 'export_type_modal' %>
<!-- /Export type modal -->

app/views/exports/new.html.erb
<div class="page-header">
  <%= link_to exports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New export</h1>
</div>

<%= render 'form' %>

app/views/exports/show.html.erb
<div class="page-header">
  <%= link_to exports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_export_path(@export), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show export</h1>
</div>

<dl class="dl-horizontal">
  <dt>File:</dt>
  <dd><%= @export.file %></dd>

  <dt>User:</dt>
  <dd><%= @export.user_id %></dd>

</dl>